// cd functions && npm run serve 
// //コード変更時に都度実行が必要。firestoreも必要なので不足。
// npm run build && firebase emulators:start
// が必要。
// VS CodeのREST Client拡張機能で実行する場合、リクエストの上にカーソルを置いて `Ctrl + Option + R` (macOS) または `Ctrl + Alt + R` (Windows/Linux) を押します。

### Insert Baby Events
POST http://127.0.0.1:5001/dev-morn-d/us-central1/insertBabyEventsFunction
Content-Type: application/json
# 認証を有効にする場合は、下の行のコメントを解除し、実際のIDトークンに置き換えてください
# Authorization: Bearer YOUR_FIREBASE_ID_TOKEN

{
  "fileName": "【ぴよログ】2025/7/13.txt",
  "content": "【ぴよログ】2025/7/13(日)\nみわ (0か月26日)\n\n05:05   母乳 左10分 / 右10分  \n07:30   母乳 右10分  \n11:30   おしっこ  \n11:45   母乳 左10分  \n13:10   母乳 右10分  \n14:00   おしっこ  \n14:00   うんち  \n14:30   ミルク 80ml  \n15:00   おしっこ  \n15:00   うんち  \n15:55   母乳 左7分  \n18:00   おしっこ  \n18:00   うんち  \n18:50   母乳 左7分 / 右10分  \n22:30   ミルク 200ml  \n22:30   うんち  \n\n母乳合計 左 34分 / 右 40分\nミルク合計 2回 180ml\n睡眠合計 0時間0分\nおしっこ合計 4回\nうんち合計 4回"
}

### Insert Baby Events
POST http://127.0.0.1:5001/dev-morn-d/us-central1/insertBabyEventsFunction
Content-Type: application/json
# 認証を有効にする場合は、下の行のコメントを解除し、実際のIDトークンに置き換えてください
# Authorization: Bearer YOUR_FIREBASE_ID_TOKEN

{
  "fileName": "【ぴよログ】2025/7/14.txt",
  "content": "【ぴよログ】2025/7/13(日)\nみわ (0か月26日)\n\n05:05   母乳 左10分 / 右10分  \n07:30   母乳 右10分  \n11:30   おしっこ  \n11:45   母乳 左10分  \n13:10   母乳 右10分  \n14:00   おしっこ  \n14:00   うんち  \n14:30   ミルク 80ml  \n15:00   おしっこ  \n15:00   うんち  \n15:55   母乳 左7分  \n18:00   おしっこ  \n18:00   うんち  \n18:50   母乳 左7分 / 右10分  \n22:30   ミルク 200ml  \n22:30   うんち  \n\n母乳合計 左 34分 / 右 40分\nミルク合計 2回 180ml\n睡眠合計 0時間0分\nおしっこ合計 4回\nうんち合計 4回"
}

### Insert Baby Events
POST http://127.0.0.1:5001/dev-morn-d/us-central1/insertBabyEventsFunction
Content-Type: application/json
# 認証を有効にする場合は、下の行のコメントを解除し、実際のIDトークンに置き換えてください
# Authorization: Bearer YOUR_FIREBASE_ID_TOKEN

{
  "fileName": "【ぴよログ】2025/7/15.txt",
  "content": "【ぴよログ】2025/7/13(日)\nみわ (0か月26日)\n\n05:05   母乳 左10分 / 右10分  \n07:30   母乳 右10分  \n11:30   おしっこ  \n11:45   母乳 左10分  \n13:10   母乳 右10分  \n14:00   おしっこ  \n14:00   うんち  \n14:30   ミルク 80ml  \n15:00   おしっこ  \n15:00   うんち  \n15:55   母乳 左7分  \n18:00   おしっこ  \n18:00   うんち  \n18:50   母乳 左7分 / 右10分  \n22:30   ミルク 200ml  \n22:30   うんち  \n\n母乳合計 左 34分 / 右 40分\nミルク合計 2回 180ml\n睡眠合計 0時間0分\nおしっこ合計 4回\nうんち合計 4回"
}

### Insert Baby Events
POST http://127.0.0.1:5001/dev-morn-d/us-central1/insertBabyEventsFunction
Content-Type: application/json
# 認証を有効にする場合は、下の行のコメントを解除し、実際のIDトークンに置き換えてください
# Authorization: Bearer YOUR_FIREBASE_ID_TOKEN

{
  "fileName": "【ぴよログ】2025/7/16.txt",
  "content": "【ぴよログ】2025/7/13(日)\nみわ (0か月26日)\n\n05:05   母乳 左10分 / 右10分  \n07:30   母乳 右10分  \n11:30   おしっこ  \n11:45   母乳 左10分  \n13:10   母乳 右10分  \n14:00   おしっこ  \n14:00   うんち  \n14:30   ミルク 80ml  \n15:00   おしっこ  \n15:00   うんち  \n15:55   母乳 左7分  \n18:00   おしっこ  \n18:00   うんち  \n18:50   母乳 左7分 / 右10分  \n22:30   ミルク 200ml  \n22:30   うんち  \n\n母乳合計 左 34分 / 右 40分\nミルク合計 2回 180ml\n睡眠合計 0時間0分\nおしっこ合計 4回\nうんち合計 4回"
}

### Insert Baby Events
POST http://127.0.0.1:5001/dev-morn-d/us-central1/insertBabyEventsFunction
Content-Type: application/json
# 認証を有効にする場合は、下の行のコメントを解除し、実際のIDトークンに置き換えてください
# Authorization: Bearer YOUR_FIREBASE_ID_TOKEN

{
  "fileName": "【ぴよログ】2025/7/17.txt",
  "content": "【ぴよログ】2025/7/13(日)\nみわ (0か月26日)\n\n05:05   母乳 左10分 / 右10分  \n07:30   母乳 右10分  \n11:30   おしっこ  \n11:45   母乳 左10分  \n13:10   母乳 右10分  \n14:00   おしっこ  \n14:00   うんち  \n14:30   ミルク 80ml  \n15:00   おしっこ  \n15:00   うんち  \n15:55   母乳 左7分  \n18:00   おしっこ  \n18:00   うんち  \n"
}